### ISSUE TITLE
How to download

### ISSUE THREAD

**Issue by bradzoob** [pema99/glsl2hlsl#3]
Hi There, I'm a bit new to Rust, this is my first compiled Rust app :)  i've read through your code but can't quite figure out how to invoke the download from shell.  Download didn't happen to be an extra compilation option that i needed to have enabled when running a cargo build?

Anyways thanks for your awesome app, you've saved me heaps of time  :)

**Comment by pema99** [comment]
I don't think I ever added that functionality to the shell. Intended way to use this has really always been through the web version at https://pema99.github.io/glsl2hlsl

Are you trying to make something automated? Wouldn't be too much of a hassle to add, but keep in mind the shadertoy api is slow and has rate limiting
